version: "2"
services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_PASSWORD: temp
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_HOST: mysql
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8080:80"
    links:
      - wpdb:mysql
  wpdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: temp
    volumes:
      - ./wp-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - wpdb:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: temp
      PMA_HOST: mysql
# volumes:
#     wp-db:
#       driver: local
