version: "2"
services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      WORDPRESS_DB_PASSWORD: temp
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_HOST: wpdb
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_connect_back=0 remote_host=172.17.0.1"
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
  wpdb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_ROOT_PASSWORD: temp
    volumes:
      - ./wp-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: temp
      PMA_HOST: wpdb