version: "2"
services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_PASSWORD: temp
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_HOST: wpdb
    volumes:
      - ../:/var/www/html
    ports:
      - "443:80"
  wpdb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_ROOT_PASSWORD: temp
    volumes:
      - wp-db:/var/lib/mysql
volumes:
    wp-db:
      driver: local
